#!/usr/bin/env php
<?php

use IAmine\Blader\Commands\BuildCommand;
use Symfony\Component\Console\Application;

if (file_exists(__DIR__.'/vendor/autoload.php')) {
	require __DIR__.'/vendor/autoload.php';
}

$application = new Application('Blader', '1.0');
$application->addCommands(
	[
		new BuildCommand(),
	]
);

$application->run();
